server {
    listen 80;
    server_name {$server_name};
    index index.php index.html index.htm;
    root {$root};

    #PHP-REWRITE-START
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/www/server/php/{$php_version}/run/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    #PHP-REWRITE-END

    #REWRITE-START
    include /www/server/panel/vhost/rewrite/{$server_name}.conf;
    #REWRITE-END

    access_log /www/wwwlogs/{$server_name}.log;
    error_log /www/wwwlogs/{$server_name}.error.log;
}
